### PR TITLE
Prepare 2.25.0-rc.0

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This prepares 2.25.0-rc.0, to be released today.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

so outstanding PRs can be merged first.

**Review by Waseem826 — APPROVED** [review]
/approve

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Review by Waseem826 — APPROVED** [review]

**Pull request merged**
