### PR TITLE
Use the new endpoints

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Related to https://github.com/kubermatic/dashboard/issues/2438.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @kgroschoff @floreks 

Can you review?

**Comment by maciaszczykm** [comment]
/hold 

For @zreigz to update delete node endpoint.

**Comment by maciaszczykm** [comment]
/hold cancel

@kgroschoff I've updated it to cover this change: https://github.com/kubermatic/kubermatic/pull/6115

PTAL

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
