### PR TITLE
Fix: Change hetzner machine size e2e tests

### LINKED ISSUE #6784: Hetzner deprecated server types
### What happened
The tests still refer to deprecated server types ( https://docs.hetzner.com/cloud/servers/deprecated-plans/ ), causing the api-e2e tests to fail because those old server types take a looooooooong time to boot up.

KKP did the same via https://github.com/kubermatic/kubermatic/pull/13647

### Expected behavior
The repository should use the newer server types for its e2e tests.

### Environment
- UI Version: any
- API Version: any
- Domain: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mohamed-rafraf**
**What this PR does / why we need it**:
This PR changes the Hetzner instance size to fix the e2e tests
**Which issue(s) this PR fixes**:

Fixes #6784 

**What type of PR is this?**

/kind failing-test
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — CHANGES_REQUESTED** [review]
`modules/web/cypress/fixtures/hetzner/sizes.json` still contains old sizes

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
