### PR TITLE
Add option to disable User SSH Key Agent from the cluster wizard

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/2986
Fixes https://github.com/kubermatic/kubermatic/issues/6383

**Special notes for your reviewer**:

**Release note**:

```release-note
Added option to disable User SSH Key Agent from the cluster wizard.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@moadqassem Please check if it looks okay for you.

**Review by kgroschoff — COMMENTED** [review]
/lgtm

/hold
(feel cancel to cancel when everything is ok)

**Comment by maciaszczykm** [comment]
/hold cancel

@kgroschoff I've applied @moadqassem suggestion in the last commit. PTAL.

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
