### PR TITLE
[release/v2.23] Prepare 2.23.18

### PR DESCRIPTION
**Pull request by mohamed-rafraf**
**What this PR does / why we need it**:
Prepare 2.23.18
**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/override pre-dashboard-web-integration-tests

It's just flaking, no need to drag this out.

**Pull request merged**
