### PR TITLE
Add valuesBlock and defaultValuesBlock and their conversion

### PR DESCRIPTION
**Pull request by SimonTheLeg**
**What this PR does / why we need it**:

This PR adds makes the new fields valuesBlock and defaultValuesBlock of AppInstalls and AppDefs available in the api. In addition on POST & PUT requests for AppInstalls/AppDefs the values/defaultValues fields are being converted to their valuesBlock/defaultValuesBlock equivalent.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12941

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
valuesBlock and defaultValuesBlock fields are now available via the api
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
Do we still need any UI changes after this?

**Comment by SimonTheLeg** [comment]
I am not 100% sure. If the UI can also handle a ValuesBlock response from the BE then I think we are already fine. 

In case we need to touch the FE code: I would appreciate if we could make all PUT/POST requests also use the new valuesBlock field (but only if it is not too much work).

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by Waseem826** [comment]
@SimonTheLeg I think you'll need to self approve this PR.

**Comment by Waseem826** [comment]
It seems like the API still uses `values` for applications added during cluster creation. It uses `valuesBlock` only for the `applicationinstallation` endpoint.
I added an application during cluster creation and the application installation returned `values` field (no `valuesBlock` field in response).
If I add/update an application installation later on (from clusters page), API returns the new `valuesBlock` field.

**Comment by SimonTheLeg** [comment]
oh I see. This is something I did not consider. I'll have a look at it and will write a fix.

**Pull request merged**
