### PR TITLE
[release/v2.25] Fix CNI plugin defaulting for Edge cloud provider

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Manual backport of https://github.com/kubermatic/dashboard/pull/6878

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix CNI plugin defaulting for Edge cloud provider
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/unhold 

Works fine in QA cc @Waseem826

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
