### PR TITLE
Multiple UI fixes

### LINKED ISSUE #4144: UI Fixes - Table columns, whats new ...
### UI Fixes
- [x] Change `Download` button on cluster page to `Get Kubeconfig`
- [x] Admin Panel - add provider preset dialog -> put preset name and provider in the same line on the last page
- [x] Admin Panel, Limits - swap checkbox and number input location
- [x] instead of automatic pop up, add a marker to help icon and what's new menu point, after it was viewed the marker disappears
image

### Dark Mode
- [x] Make notifications background a shade lighter (the shade of cards maybe?)
- [x] Tabs (like cluster/external cluster) bottom line needs to be lighter `#464647` same with the outline/border of the search bar

#### Main Interface
Clusters		- 25, 30, 15, 15, 15
External clusters - 30, 30, 20, 20
MDs		- 25, 30, 10, 10, 10, 15
Nodes		- 35, 15, 30, 15
Cluster Templates - 30, 20, 20, 30
Backups		- 25, 20, 15, 15, 10, 15
Snapshots	- 	30, 20, 20, 30
Restores		- 30, 15, 15, 25, 15
SSH keys		- 35, 40, 25
Members		- 35, 40, 25
Service accounts - 	50, 25, 25
Service accounts token - 	50, 25, 25

#### Admin Panel
Dynamic Datacenters	- 30, 30, 20, 20
Provider Presets - 	25, 60, 15
OPA - Default Con. - 	20, 20, 15, 35, 10 (I believe applies to column can contain several things, if that's not the case then we can give it less space)
OPA - Allowed Reg.	- 50, 50
Metering Reports 	 - 60, 20, 20
Accounts		 - 30, 15, 25, 15, 15
Administrators - 		40, 60

### PR DESCRIPTION
**Pull request by kgroschoff**
### What this PR does / why we need it
Multiple UI fixes, mainly related to table column width and changelog display logic.

### Which issue(s) this PR fixes

Fixes #4144

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
PTAL @maciaszczykm @floreks

**Comment by kgroschoff** [comment]
/hold cancel

@maciaszczykm can you lgtm again, please? Rebased due to the e2e fix

**Comment by maciaszczykm** [comment]
@kgroschoff Sure.

/lgtm

**Pull request merged**
