### PR TITLE
[release/v2.23] Prepare v2.23.7 release

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This prepares the v2.23.7 release scheduled for next Tuesday.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind documentation
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
We should update the version in `modules/web/Makefile` as well.

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by embik** [comment]
> We should update the version in `modules/web/Makefile` as well.

Good catch. I did a search and replace on 2.23.6 and missed that this file was still on 2.23.5.

**Pull request merged**
