### PR TITLE
Align enforce setting behavior

### PR DESCRIPTION
**Pull request by maciaszczykm**
### What this PR does / why we need it
It changes the current behavior of enforce OPA checkbox. Right now it will enforce setting that is selected in the first checkbox (enable by default). I've changed "enforce" label to "enforce defaults" to make it more clear.

### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/3355.

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @kgroschoff 

Please check if the applied logic is fine.

**Comment by kgroschoff** [comment]
So just for clarification:
Admin Settings - OPA enabled + enforced = wizard checkbox is checked and disabled
Admin Settings - OPA not enabled + enforced = wizard checkbox is only disabled, but not checked
Right?

I think the original idea of your issue was to check + disable every time when `enforce` is true, because we have some `enforceXYZ` things on dc level. But tbh I think the `Enforce Default` is a great idea and makes it more clear, that it only works in combination with the `Enable` option.

Code looks good.

**Comment by floreks** [comment]
I think that on the DC level we do not actually have cleanup nor OPA settings. If that is true the idea was to make `enforce` manipulate enable/disable status of the field and `enable by default` would check/uncheck it.

**Comment by maciaszczykm** [comment]
> So just for clarification:
Admin Settings - OPA enabled + enforced = wizard checkbox is checked and disabled
Admin Settings - OPA not enabled + enforced = wizard checkbox is only disabled, but not checked
Right?

True.

**Comment by maciaszczykm** [comment]
I was checking it yesterday and there is nothing OPA or cluster-cleanup related in the DC settings.

If that's okay then PTAL @kgroschoff.

**Comment by maciaszczykm** [comment]
I'll have to adjust tests.

**Comment by kgroschoff** [comment]
Yes there is nothing for OPA on dc level.

I'm waiting for the tests then ;)

**Comment by maciaszczykm** [comment]
/hold

To take a look on tests.

**Comment by maciaszczykm** [comment]
@kgroschoff @floreks Can one of you recheck?

**Pull request merged**
