### PR TITLE
Re-Name Node Deployment to Machine Deployment

### PR DESCRIPTION
**Pull request by cedi**
### What this PR does / why we need it
currently on some places the term "Machine Deployment" is used while in
some others "Node Deployment" is used.

This PR fixes this by re-naming everything that is left on "Node
Deployment" to "Machine Deployment"

### Release note

```release-note
Re-Naming every occurrence of "Node Deployment" in the UI to "Machine Deployment"
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
I will cancel the cherry pick once it will be created, added it automatically. 

@cedi Can you reformat files?

**Comment by cedi** [comment]
> I will cancel the cherry pick once it will be created, added it automatically.
> 
> @cedi Can you reformat files?

What shall I reformat? I didn't change any formatting

**Comment by maciaszczykm** [comment]
But you have changed the file contents and the static check has failed:

```
> kubermatic-dashboard@2.14.0-rc.2 check:ts /home/prow/go/src/github.com/kubermatic/dashboard
> gts check
version: 12
/home/prow/go/src/github.com/kubermatic/dashboard/src/app/cluster/services/node.service.ts
  158:53  error  Replace `'Could·not·remove·the·<strong>${md.name}</strong>·machine·deployment'` with `⏎······················'Could·not·remove·the·<strong>${md.name}</strong>·machine·deployment'⏎····················`  prettier/prettier
✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

You need to run `npm run fix` (https://github.com/kubermatic/dashboard/blob/release/v2.15/package.json#L28) and commit the changes.

**Comment by cedi** [comment]
Sorry @maciaszczykm, got a little confused earlier.
Pushed the changes to my branch :)

**Comment by floreks** [comment]
`package.json` and `package-lock.json` definitely need to be reverted. They are only meant to be updated when we update dependencies.

**Comment by maciaszczykm** [comment]
@cedi Sure, no problem. Can you please revert the files that @floreks has mentioned?

/test all

**Pull request merged**
