### PR TITLE
Bump package versions

### PR DESCRIPTION
**Pull request by Waseem826**
**What does this PR do / Why do we need it**:
Most of the npm packages are now bumped to latest versions. There are few packages (e.g. `swagger-ui`, `cypress`) which require extra migration changes so those are not updated in this PR.

**Which issue(s) this PR fixes** :

Fixes #

**Special notes for your reviewer**:
Please make sure that you run this PR locally and perform some sanity checking as well.
In order to make sure that installation of these packages works without any issues please follow these steps:
- `npm cache clear --force`
- `rm -R node_modules/`
- `npm ci`

**Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by KhizerRehan** [comment]
@Waseem826 
I see following warning on build of dashboard:
- `clone-deep` do we need to put it under `allowedCommonJsDependencies` ?
- 2nd one can be ignored as it is dependency of `swagger-ui` 
c7bf8dec80000d6db0660f3b24e26e03

**Comment by KhizerRehan** [comment]
Otherwise 
- build works fine
- serve works fine
- basic sanity testing done

/lgtm

**Comment by Waseem826** [comment]
> @Waseem826 I see following warning on build of dashboard:
> 
> * `clone-deep` do we need to put it under `allowedCommonJsDependencies` ?
> * 2nd one can be ignored as it is dependency of `swagger-ui`
> 
> c7bf8dec80000d6db0660f3b24e26e03

`clone-deep` is not in our `package.json` so I think we should ignore that for now.

**Comment by xrstf** [comment]
For the next release, please do this _before_ we do the code freeze.

**Pull request merged**
