### PR TITLE
[release/v2.22] Bump version v2.22.1

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
- Update KKP version in Dashboard API
- Bump versions to v2.22.1
- Update `changelog.json`

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by hdurand0710** [comment]
Please update the title from [release/v2.21] tp [release/v2.22]

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Review by hdurand0710 — APPROVED** [review]

**Pull request merged**
