### PR TITLE
Edit MD Dialog Enhancements

### LINKED ISSUE #5085: Edit MD Dialog UI/UX Enhancements
- [x] remove name text field (it's not editable and we have it in the description of the modal anyway)
image

- [x] put replica and kublet version, and disk type and disk size on one line if possible (see screenshot at the top) 
- [x] instead of a "Show Hide Advanced Settings" bottom left we should use the unfoldable element we use elsewhere
image

- [ ]  Add "cut off shadow" to indicate scrollable area 
image

Note:
when hiding and unhiding advanced settings or the like the "changed node specification nodes will be recreated" message shouldn't appear, in other words, only make that message appear when it makes sense and when it actually happens

### PR DESCRIPTION
**Pull request by ahmadhamzh**
**What this PR does / why we need it**:
Enhancement for machine deployment edit dialog 
**Which issue(s) this PR fixes**:

Fixes #5085

**Special notes for your reviewer:**
show disk type and disk size in one row is only for following providers
 -  AWS, 
 - GCP 
 - Alibaba

**What type of PR is this?**
/kind design

```release-note
change the showing advance settings button to expanding arrow in the edit md dialog  and rearrange some fields in it.
```
```documentation
NONE
```

### CODE REVIEW

**Review by KhizerRehan — CHANGES_REQUESTED** [review]
Feedback PTAL

**Comment by KhizerRehan** [comment]
Lastly, Does this enhancement is for MD dialog or all over the Edit Dialogs? As per our discussion i thought it was for MD dialog only.

**Comment by ahmadhamzh** [comment]
> Lastly, Does this enhancement is for MD dialog or all over the Edit Dialogs? As per our discussion i thought it was for MD dialog only.

MD dialog but the `Add "cut off shadow" to indicate scrollable area` i think it need to be to all dialogs

**Review by Waseem826 — CHANGES_REQUESTED** [review]

**Review by KhizerRehan — APPROVED** [review]

**Pull request merged**
