### PR TITLE
Introduce new structure to the Dashboard repository

### LINKED ISSUE #5227: Introduce new structure to the Dashboard repository
**User story**
As as developer, I want to see clear distinction between frontend and backend code inside the dashboard repository. We can use [Kubernetes Dashboard's structure](https://github.com/kubernetes/dashboard/tree/master/modules) as an example.

**Acceptance criteria**
- Introduce a new structure to the repository, making it clear if code belong to the frontend or backend.
- Consider adding some prefixes to makefile targets as we decided to share makefile between FE and BE.
- Adjust prowjobs and scripts in ./hack directory to this new structure.

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
This PR refactors the dashboard repository structure and splits the API and Frontend code into separate isolable modules.

**Which issue(s) this PR fixes**:

Fixes #5227

**What type of PR is this?**

/kind chore
/kind feature
/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Code and dependencies for API and Web have been split into dedicated modules.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/retest pre-dashboard-web-integration-tests-c

flaky flake flakez

**Comment by ahmedwaleedmalik** [comment]
/retest pre-dashboard-web-integration-tests-ce

flaky flake flakez

**Comment by ahmedwaleedmalik** [comment]
/test pre-dashboard-web-integration-tests-ce

flaky flake flakez

**Review by Waseem826 — APPROVED** [review]
/hold

**Pull request merged**
