### PR TITLE
Bump version to v2.22.0-rc.0

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
Bumping version to `v2.22.0-rc.0` so we can cut a first RC release in the near future.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
@embik Isn't this supposed to be a release candidate now? Why are we still using a beta release?

cc @xmudrii @Waseem826

**Comment by embik** [comment]
> @embik Isn't this supposed to be a release candidate now? Why are we still using a beta release?
> 
> cc @xmudrii @Waseem826

We will cut a release candidate for sure, but since things are still merging I would like to cut a beta release this week and a RC after that.

**Comment by ahmedwaleedmalik** [comment]
> > @embik Isn't this supposed to be a release candidate now? Why are we still using a beta release?
> > cc @xmudrii @Waseem826
> 
> We will cut a release candidate for sure, but since things are still merging I would like to cut a beta release this week and a RC after that.

We have a release no Monday, or let's say next week, then does cutting a RC on Monday really makes sense? I'd rather wait till tonight and cut an RC tomorrow.

**Review by pkprzekwas — APPROVED** [review]
/lgtm

**Pull request merged**
