### PR TITLE
Add network configuration for user clusters

### PR DESCRIPTION
**Pull request by maciaszczykm**
### Which issue(s) this PR fixes
Closes https://github.com/kubermatic/dashboard/issues/3406.

### Release note
```release-note
Added network configuration for user clusters.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Zrzut ekranu 2021-06-28 o 16 05 51

It's ready for a review. 

/assign @kgroschoff @floreks 

I have one thing to clarify as the API saves the data correctly [1] but does not return any information about cluster networking once it is saved. @irozzo-1A can you tell us if this is intended or if we should modify the API to return this information back to UI (entry in the `ConvertInternalClusterToExternal` is missing) and display it?

[1] Zrzut ekranu 2021-06-28 o 15 58 27

**Comment by maciaszczykm** [comment]
E2E have failed at Alibaba instance sizes request.

/retest

**Review by floreks — APPROVED** [review]
/lgtm

**Comment by irozzo-1A** [comment]
> Zrzut ekranu 2021-06-28 o 16 05 51
> 
> It's ready for a review.
> 
> /assign @kgroschoff @floreks
> 
> I have one thing to clarify as the API saves the data correctly [1] but does not return any information about cluster networking once it is saved. @irozzo-1A can you tell us if this is intended or if we should modify the API to return this information back to UI (entry in the `ConvertInternalClusterToExternal` is missing) and display it?
> 
> [1] Zrzut ekranu 2021-06-28 o 15 58 27

Yep, definitely, we should modify the API to return the information back.

**Comment by maciaszczykm** [comment]
/hold

For API changes and e2e test verification.

**Comment by maciaszczykm** [comment]
/hold cancel

@floreks PTAL.

**Pull request merged**
