### PR TITLE
Fix Makefile not producing the right image repository

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
Determining the correct repository to build and push for was broken, this should fix it.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Review by KhizerRehan — APPROVED** [review]

**Pull request merged**
