### PR TITLE
[release/v2.22] Changelog update

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
Adding information about security patch in web-terminal.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by pkprzekwas** [comment]
/test 
pre-dashboard-web-integration-tests

**Pull request merged**
