### PR TITLE
Add K8sGPT and add default user and webshell user for bashrc

### PR DESCRIPTION
**Pull request by mfahlandt**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes  [#13026](https://github.com/kubermatic/kubermatic/issues/13026)

**What type of PR is this?**
/kind feature
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Add K8sGPT to the Webshell
```

**Documentation**:
```documentation
TBD
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by mfahlandt** [comment]
I don't know why the test is failing, I don't see anything on my side causing it 😔

**Pull request merged**
