### PR TITLE
[release/v2.21] Provide option for autoscaling nodes

### PR DESCRIPTION
**Pull request by Waseem826**
**What this PR does / why we need it**:
This PR is cherrypick of #5369 and #5398

**What type of PR is this?**

/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Provide options for autoscaling nodes
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
/hold
Wait for backend cherrypick PR

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
