### PR TITLE
Fix cluster search

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/2722

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@kgroschoff Please take a look :)

**Comment by kgroschoff** [comment]
Works like a charm, but the table looks wrong now. The line under the last item shouldn't be visible 🙈 
line

**Comment by maciaszczykm** [comment]
@kgroschoff It's fixed now. PTAL

**Pull request merged**
