### PR TITLE
fix a bunch of typos

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
https://github.com/crate-ci/typos found a lot of false positives, but also lots of actual typos. :-)

**Which issue(s) this PR fixes** :

Fixes #

**Special notes for your reviewer**:

**Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
@xrstf `pre-dashboard-check-static` failed due to couple of minor formatting issues which can be fixed by `npm run fix`

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by Waseem826** [comment]
/hold
To silence kubermatic-triage-bot

**Review by KhizerRehan — APPROVED** [review]

**Review by Waseem826 — APPROVED** [review]

**Pull request merged**
