### PR TITLE
Added Alibaba VSwitch

### PR DESCRIPTION
**Pull request by kgroschoff**
### What this PR does / why we need it
Added option to select Alibaba VSwitch from list

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
PTAL @maciaszczykm / @floreks

**Comment by floreks** [comment]
After discussing with @zreigz and @maciaszczykm it would be safer to use input with autocomplete rather than combobox. As we do not know exactly how alibaba works it might be better to give users the option to manually provide vSwitch value if needed.

Other than that it lgtm.

**Comment by kgroschoff** [comment]
@floreks done, PTAL

**Pull request merged**
