### PR TITLE
Revert "add option to enable konnectivity on user-cluster"

### PR DESCRIPTION
**Pull request by PratikDeoghare**
Reverts kubermatic/dashboard#3661 because API doesn't provide information about feature gates. We need that info to show/hide Konnectivity UI components. 

Ref #3672

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@PratikDeoghare Release note is missing.

**Comment by floreks** [comment]
> Release note is missing

I have manually added a label for `none`. PR template was not used...

**Pull request merged**
