### PR TITLE
Fix add icon placement

### PR DESCRIPTION
**Pull request by maciaszczykm**
### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/3430.

### Special notes for your reviewer
Zrzut ekranu 2021-06-18 o 09 38 05
Zrzut ekranu 2021-06-18 o 09 37 49
Zrzut ekranu 2021-06-18 o 09 37 37

### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
It seems that now the text isn't centered. Can you fix it, please?

**Comment by maciaszczykm** [comment]
@kgroschoff You're right, it's fixed now.

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
