### PR TITLE
Fix ui in edit provider dialog

### LINKED ISSUE #4159: Edit provider dialog informations are misplaced
In the edit provider dialog the informations like provider icon and "hide upon creation" aren't aligned. Also the "Preset Name" field is no longer needed, as it is already in the description text.
Additionally the scrollbar isn't correctly placed.

preset

### PR DESCRIPTION
**Pull request by kgroschoff**
### What this PR does / why we need it
Fix ui in edit provider dialog. Informations + Scrollbar were misplaced

### Which issue(s) this PR fixes

Fixes #4159

### Special notes for your reviewer
edit

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
PTAL @maciaszczykm @floreks

**Comment by maciaszczykm** [comment]
If we are on it then I'd put the provider before the hide upon creation status.

**Comment by kgroschoff** [comment]
Sorry @maciaszczykm missed your comment yesterday. Moved the provider logo.
xx

**Pull request merged**
