### PR TITLE
Update dependencies and Node to v16

### PR DESCRIPTION
**Pull request by maciaszczykm**
### Which issue(s) this PR fixes
Closes https://github.com/kubermatic/dashboard/issues/3827.

### Special notes for your reviewer
Build image was updated in https://github.com/kubermatic/infra/pull/1557.

For Node >=16.10 it might be required to add `--legacy-peer-deps` param while using `npm i` command. `npm ci` works like before.

```
➜ node --version
v16.13.0

➜ npm outdated    
Package                            Current   Wanted  Latest  Location                                        Depended by
@angular-devkit/build-angular      12.2.13  12.2.13  13.0.2  node_modules/@angular-devkit/build-angular      kubermatic-dashboard
@angular/animations                12.2.13  12.2.13  13.0.1  node_modules/@angular/animations                kubermatic-dashboard
@angular/cdk                       12.2.13  12.2.13  13.0.1  node_modules/@angular/cdk                       kubermatic-dashboard
@angular/cli                       12.2.13  12.2.13  13.0.2  node_modules/@angular/cli                       kubermatic-dashboard
@angular/common                    12.2.13  12.2.13  13.0.1  node_modules/@angular/common                    kubermatic-dashboard
@angular/compiler                  12.2.13  12.2.13  13.0.1  node_modules/@angular/compiler                  kubermatic-dashboard
@angular/compiler-cli              12.2.13  12.2.13  13.0.1  node_modules/@angular/compiler-cli              kubermatic-dashboard
@angular/core                      12.2.13  12.2.13  13.0.1  node_modules/@angular/core                      kubermatic-dashboard
@angular/forms                     12.2.13  12.2.13  13.0.1  node_modules/@angular/forms                     kubermatic-dashboard
@angular/localize                  12.2.13  12.2.13  13.0.1  node_modules/@angular/localize                  kubermatic-dashboard
@angular/material                  12.2.13  12.2.13  13.0.1  node_modules/@angular/material                  kubermatic-dashboard
@angular/platform-browser          12.2.13  12.2.13  13.0.1  node_modules/@angular/platform-browser          kubermatic-dashboard
@angular/platform-browser-dynamic  12.2.13  12.2.13  13.0.1  node_modules/@angular/platform-browser-dynamic  kubermatic-dashboard
@angular/router                    12.2.13  12.2.13  13.0.1  node_modules/@angular/router                    kubermatic-dashboard
cypress                              8.7.0    8.7.0   9.0.0  node_modules/cypress                            kubermatic-dashboard
cypress-fail-fast                    3.2.0    3.2.0   3.3.0  node_modules/cypress-fail-fast                  kubermatic-dashboard
flag-icon-css                        3.5.0    3.5.0   4.1.5  node_modules/flag-icon-css                      kubermatic-dashboard
lint-staged                         11.2.6   11.2.6  12.0.2  node_modules/lint-staged                        kubermatic-dashboard
ngx-cookie-service                  12.0.3   12.0.3  13.0.0  node_modules/ngx-cookie-service                 kubermatic-dashboard
stylelint                           14.0.1   14.0.1  14.1.0  node_modules/stylelint                          kubermatic-dashboard
typescript                           4.3.5    4.3.5   4.4.4  node_modules/typescript                         kubermatic-dashboard
```

~~https://github.com/angular/components/issues/23907 needs to be solved to make the unit tests pass.~~ I had to revert to Angular LTS version as v13 is not stable enough at the moment.

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/hold

Until upstream issues will be fixed.

**Comment by kgroschoff** [comment]
mocked e2e tests showing following

```
  Running:  providers/openstack.spec.ts                                                   (11 of 24)

<--- Last few GCs --->

[772:0x5084950]   831386 ms: Mark-sweep (reduce) 2043.4 (2054.8) -> 2042.5 (2054.8) MB, 2856.7 / 0.0 ms  (average mu = 0.132, current mu = 0.009) allocation failure scavenge might not succeed
[772:0x5084950]   834188 ms: Mark-sweep (reduce) 2043.6 (2051.8) -> 2042.5 (2052.8) MB, 2790.1 / 0.0 ms  (average mu = 0.072, current mu = 0.004) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa222f0 node::Abort() [/usr/local/bin/node]
 2: 0x96411f node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb97f1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb98297 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xd52fd5  [/usr/local/bin/node]
 6: 0xd53b5f  [/usr/local/bin/node]
 7: 0xd61beb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0xd657ac v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0xd2af4d v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0xd271a9 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/local/bin/node]
11: 0xd27264 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
12: 0xeb545e  [/usr/local/bin/node]
13: 0xeb570d  [/usr/local/bin/node]
14: 0xc0aee9 v8::internal::Builtin_ArrayUnshift(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x1423359  [/usr/local/bin/node]
```

Not sure if this is a flake or something that is caused by your changes? Do you have an idea?

Otherwise I think your pr looks good.

**Comment by maciaszczykm** [comment]
@kgroschoff Adjusted the limits, now Cypress should be more stable.

**Comment by maciaszczykm** [comment]
/hold

There is issue with Cypress after version bump.

**Pull request merged**
