### PR TITLE
Update OPA enforcement message

### PR DESCRIPTION
**Pull request by maciaszczykm**
### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/4063.

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
@maciaszczykm check-static is failing 
```
/home/prow/go/src/github.com/kubermatic/dashboard/src/app/cluster/details/cluster/edit-cluster/component.ts
  97:6  error  Delete `⏎··`  prettier/prettier
```

Apart from that lgtm

**Comment by maciaszczykm** [comment]
@kgroschoff Yes, it looks my IDE settings got updated. PTAL

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
