### PR TITLE
Update KubeVirt operating system image support

### PR DESCRIPTION
**Pull request by Waseem826**
**What this PR does / why we need it**:
KubeVirt changes:
- Removed custom images
- Converted `Operating System Image` to a dropdown with options specific to selected operating system.

https://user-images.githubusercontent.com/13975988/213213697-746b0c89-60ec-4beb-9549-fb62c4b96e39.mov

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Converted Operating System Image to a dropdown with options specific to selected operating system.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
cc @mfranczy

**Comment by mfranczy** [comment]
thanks, looks great!

**Pull request merged**
