### PR TITLE
Add validation for floats

### LINKED ISSUE #3664: Minimum spot instance price input accepts invalid value?
**What happened?**:
Zrzut ekranu 2021-09-8 o 14 49 10

**What should happen?**: Should the field be invalid in that case?

**How to reproduce?**: Go to wizard, pick AWS as provider and select spot instance checkbox.

**Environment**
- UI Version: master
- API Version: master
- Domain: dev
- Others: Chrome on macOS

### PR DESCRIPTION
**Pull request by kgroschoff**
### What this PR does / why we need it
Add validation for floats

### Which issue(s) this PR fixes

Related to #3664

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by floreks** [comment]
Actually, string validation for float is not what we need here. Since it is a field of type `number` it already accepts only digits and `.` or `,`. Example entry provided by Marcin that is acceptable now actually returns a `control.value` set to `null`. Another issue is that this new validator does not allow an empty value and basically makes it required since providing a value and then removing it returns `null`.

**Comment by kgroschoff** [comment]
@floreks Oh I've missed your comment. Good catch with the empty value that should definitely be allowed, even after change. Nevertheless, since this solution seems to be not the correct one, should I close this pr and we take a look into this issue at a later point again?

**Pull request closed without merging**
