### PR TITLE
Extend cluster details view by tab User Cluster Alert Rules

### LINKED ISSUE #3422: Extend cluster details view by tab "User Cluster Alert Rules" for MLA
Currently, the following endpoints are implemented for alert rule groups:
```
GET /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups
GET /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups/{rulegroup_id}
POST /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups
PUT  /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups/{rulegroup_id}
DELETE /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups/{rulegroup_id}
```
and a rule group looks like following:
```
{
  "data": "bmFtZTogdGVzdC0yCnJ1bGVzOgojIEFsZXJ0IGZvciBhbnkgaW5zdGFuY2UgdGhhdCBpc",
  "type": "Logs"
}
```
It has a `data` field, which is a raw yaml, for example: 
```
name: example
rules:
  - alert: HighThroughputLogStreams
    expr: sum by(container)(rate({job=~"kube-system/.*"}[1m])) > 50
    for: 1m
```
and it has a `type` field, which can be `Metrics` or `Logs`.
User should be able to manage rule groups when MLA Logging and/or Monitoring are/is enabled for the user cluster via a tab in cluster details.

Options:
- Add -> yaml editor for the data, and a select box for choosing the type `Metrics` or `Logs`
- Update -> same as add
- Delete
- List -> providing a dropdown menu (like the `Filter by` menu for OPA constraints) to allow users to list rule groups by type. Filtering is implemented (For Logs type, PR is under review: https://github.com/kubermatic/kubermatic/pull/7202) at API side as query parameters:
```
List all rule groups: 
GET /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups
List rule groups with `Metrics` type: 
GET  /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups??type=Metrics
List rule groups with `Logs` type: 
GET  /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups??type=Logs
```

### LINKED ISSUE #3426: Replace "MLA" prefix with "User Cluster"
Currently, we have `MLA` prefixed for all MLA-related options, and we can replace it with `User Cluster` to make it clear to both KKP admins and users.

Admin Panel:
- [ ] MLA Logging -> User Cluster Logging
- [ ] MLA Monitoring -> User Cluster Monitoring

Cluster Creation Page:
- [ ] MLA Logging -> User Cluster Logging
- [ ] MLA Monitoring -> User Cluster Monitoring

Cluster Details Tabs:
- [ ] MLA Alertmanager Config -> Alertmanger Config or User Cluser Alertmanager Config?

For the Cluster Details Tabs, I am not sure if we should have `User Cluster` prefix since that will make the tab name quite long.
Any thought? @shaase-ctrl @kgroschoff @rastislavs

### PR DESCRIPTION
**Pull request by kgroschoff**
### What this PR does / why we need it
Extend cluster details view by tab User Cluster Alert Rules

### Which issue(s) this PR fixes

Fixes #3422
Fixes #3426

### Release note

```release-note
Extend cluster details view by tab User Cluster Alert Rules for MLA
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
PTAL @maciaszczykm / @floreks 

Valid yaml is e.g.
```
name: example
rules:
  - alert: HighThroughputLogStreams
    expr: sum by(container)(rate({job=~"kube-system/.*"}[1m])) > 50
    for: 1m
```

**Comment by floreks** [comment]
code LGTM too

**Comment by floreks** [comment]
After testing I have noticed that `rulegroups` endpoint tends to fail and stops refreshing. User than has to completely refresh the page to actually see newly added rules. It should not stop refreshing on error.

**Comment by maciaszczykm** [comment]
/lgtm cancel

Please check @floreks comment.

**Comment by kgroschoff** [comment]
Hm, didn't happen to me, but I will check. Thanks 👍

**Comment by kgroschoff** [comment]
@floreks catching errors now. Can you please check if this solves the problem?

**Comment by floreks** [comment]
Seems to be working fine now.

**Pull request merged**
