### PR TITLE
Enable OSM by default

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:
This PR does the following things:

- Enable Operating System Manager by default in the `Cluster Settings` step in the cluster creation wizard.
- Remove usage of the `experimental` keyword with OSM
- Display health status for OSM and Kubernetes dashboard on cluster summary page.
- Some other fixes

**Which issue(s) this PR fixes** :

Fixes #

**Special notes for your reviewer**:

**Release Note**:

```release-note
Operating System Manager is enabled by default for new clusters.
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/hold

This is ready to be reviewed and merged. I'll remove the `hold` from this later.

**Review by Waseem826 — APPROVED** [review]
/approve

**Review by Waseem826 — APPROVED** [review]

**Comment by ahmedwaleedmalik** [comment]
Closing this PR because of some stupid issue with the CI. It keeps picking some old interim commit `g50ad0783` which is no longer there in my branch.

**Pull request closed without merging**
