### PR TITLE
migrate to yq4

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
It's time to migrate to yq4. See https://mikefarah.gitbook.io/yq/upgrading-from-v3 for more information.

I chose to make it explicit what version we're using for now, in order to slowly get rid of yq3 over the next few PRs. It is a bit annoying that devs would need a  `yq4` binary on their machines, but I suspect many have v3 and v4 around, like I do.

I have no idea why exactly we had to YAML-to-JSON the kubeconfig, and also why it should not have been encoded. So I simply removed `yq` here alltogether.

**Which issue(s) this PR fixes** :

Fixes #

**Special notes for your reviewer**:

**Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/lgtm

**Comment by ahmedwaleedmalik** [comment]
@xrstf the full-e2e tests will/can be ignored. They are broken but they should be fixed in a separate PR. I've already communicated that to `sig-ui`.

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
