### PR TITLE
Bump version to v2.25.0-beta.2

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:

Prepares a new v2.25.0-beta.2 release to roll out to QA.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by embik** [comment]
/retest

These data races are getting really bad.

**Pull request merged**
