### PR TITLE
Bump version to KKP 2.23.0-beta.2

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
What it says on the title. Also pulls in the latest KKP commit (https://github.com/kubermatic/kubermatic/commit/0583e6babb9e9af77475e7613079efdd8a899586).

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/retest

**Comment by embik** [comment]
/hold

This will not work until we fix image builds for kubermatic/kubermatic.

**Review by Waseem826 — APPROVED** [review]

**Pull request merged**
