### PR TITLE
Rename title for MD dialog specific to cloud provider term

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What this PR does / why we need it**:
This PR updates title to provider specific term for MD dialog

https://user-images.githubusercontent.com/17727069/185615746-ea0f1610-44c7-4713-a5dc-12bc4980e212.mp4

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind design

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
None
```

**Documentation**:

```documentation
None
```

### CODE REVIEW

**Comment by Waseem826** [comment]
What about edit machine deployment dialog? Do we need to change it there too?

**Comment by KhizerRehan** [comment]
> What about edit machine deployment dialog? Do we need to change it there too?

No, it's for Add case as per confirmed with @imharshita. you can merge this change @Waseem826

**Pull request merged**
