### PR TITLE
Improve e2e tests stability

### PR DESCRIPTION
**Pull request by floreks**
- Added new `TrafficMonitor` class to easily wait for request or expect a specific response from the API with the ability to retry.
- Updated `workerCount` in test to 100
- Refactored some magic strings to enums.
- Fixed some issues with properly waiting for project and selecting it. (full page refresh seems to help, but we might have some underlying issue here in the frontend)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by floreks** [comment]
5x success in a row. I think it's quite stable now :slightly_smiling_face: 

@kgroschoff PTAL

**Comment by kgroschoff** [comment]
Awesome 🎉 
I think this could also be cherry-picked into 2.14. WDYT?

/lgtm

**Comment by floreks** [comment]
> Awesome 
> I think this could also be cherry-picked into 2.14. WDYT?
> 
> /lgtm

I think so.

/cherry-pick release/v2.14

**Pull request merged**
