### PR TITLE
Fix default operating system selection

### LINKED ISSUE #3199: Default operating system is not selected for Anexia
**What happened?**: There is no default operating system for Anexia.

**What should happen?**: The only one available option should be selected.

**How to reproduce?**:
Zrzut ekranu 2021-03-29 o 08 22 27

**Environment**
- UI Version: master
- API Version: master
- Domain: dev
- Others:

### PR DESCRIPTION
**Pull request by kgroschoff**
**What this PR does / why we need it**:
Fix default operating system selection

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3199

**Special notes for your reviewer**:
/

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by floreks** [comment]
Fix for this is already bundled with the e2e updates: https://github.com/kubermatic/dashboard/pull/3198/files#diff-63e050f0feb764530b887203b5248c3441e4f5d9aebd3716616df2ad4526f83e

**Comment by kgroschoff** [comment]
I see. 😅  But actually the default system template also is broken
```
if (this._datacenterSpec) {
    return this._getDefaultSystemTemplate(this.provider);
}
```
since this part always returns Ubuntu first
```
if (this.isOperatingSystemSupported(this._nodeDataService.operatingSystem)) {
      return this._nodeDataService.operatingSystem;
}
```

Should I then just remove the anexia part or do you want to take over the change to your PR? WDYT?

**Comment by floreks** [comment]
This part is actually only used when editing since `this._nodeDataService.operatingSystem` is empty when using wizard. It is filled with initial data when editing node.
```typescript
if (this.isOperatingSystemSupported(this._nodeDataService.operatingSystem)) {
      return this._nodeDataService.operatingSystem;
}
```

The actual code that runs inside the wizard would be then
```typescript
    if (this._datacenterSpec) {
      return this._getDefaultSystemTemplate(this.provider);
    }

    if (this.isProvider(NodeProvider.ANEXIA)) {
      return OperatingSystem.Flatcar;
    }

    return OperatingSystem.Ubuntu;
```

Getting system from datacenterspec should be the last step as it only supports vsphere right now and even though other datacenters can have this spec defined, they do not provide OS template that we could map. That's why I have simply switched those 2.

**Comment by kgroschoff** [comment]
Okay. But hasn't the anexia part then come first? Because `_getDefaultSystemTemplate` currently always is returning Ubuntu too, but Anexia only has Flatcar 🤔

**Comment by floreks** [comment]
It does come first in my fix. I have pasted the current code with the issue present.

**Comment by kgroschoff** [comment]
sorry then I just close here

**Pull request closed without merging**
