### PR TITLE
[release/v2.24]Bump version changes for KKP Apr 2024 patch release

### PR DESCRIPTION
**Pull request by archups**
**What this PR does / why we need it**:
This PR is for bumping the version changes for KKP Apr 2024 patch release 2.24.6

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind documentation
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by embik** [comment]
/retest

looks like flakes to me.

**Review by embik — APPROVED** [review]

**Pull request merged**
