### PR TITLE
Revert go back button function

### PR DESCRIPTION
**Pull request by ahmadhamzh**
### What this PR does / why we need it
revert a method that been deletes by mistake for go back button in external cluster view 

```release-note
NONE
```

### CODE REVIEW

**Comment by KhizerRehan** [comment]
Hi, @ahmadhamzh it works as before but 1 thing i noticed is was adding `#1` fragment on URL and i know the reason why it is there due to https://github.com/kubermatic/dashboard/pull/4552/files#diff-2791abe7693e2e58bd36c3939d51d1e9c7ea3e0df76452284264b55ffa3c9857R167 this line and it is needed inorder to switch tab from `Cluster to External Clusters` tab 

clusterIndex 0 -> Clusters Tab
clusterIndex 1 -> External Clusters

https://user-images.githubusercontent.com/17727069/172537358-0a31a58c-3efa-4487-970e-9a6c9e5943b2.mp4

**Comment by maciaszczykm** [comment]
Why changing package lock?

**Comment by KhizerRehan** [comment]
https://github.com/kubermatic/dashboard/pull/4552#issuecomment-1149595731

- cron-validator package is introduced you might need to sync with master branch: @ahmadhamzh 
[Add retention parameter to metering schedule configuration #4478](https://github.com/kubermatic/dashboard/pull/4552#issuecomment-1149595731)

**Pull request merged**
