### PR TITLE
Bump to v2.23.0-rc.0

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This bumps the version to v2.23.0-rc.0 in preparation for the release candidate release.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
Missing version bump in `package.json` and `package-lock.json` of `web` module.

**Comment by embik** [comment]
> Missing version bump in `package.json` and `package-lock.json` of `web` module.

_sigh_ 

Thanks for catching. I really need to change my regex.

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
