### PR TITLE
Use the new endpoints

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Related to https://github.com/kubermatic/dashboard/issues/2438.

**Special notes for your reviewer**:

**Release note**:

```release-note
The seed datacenter param was removed from the path. It is no longer required thanks to the switch to the new version of API.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @floreks 

Please take a look, it seems that I've checked all the stuff manually, but it would be great if you could do second check :)

**Review by floreks — APPROVED** [review]

**Comment by maciaszczykm** [comment]
@floreks PTAL, I've resolved the conflicts.

**Pull request merged**
