### PR TITLE
Display GPU count for Alibaba instance types

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/3094

**Special notes for your reviewer**:

**Release note**:

```release-note
Added GPU count display for Alibaba instance types.
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
apart from the failing unit test, it is looking good to me

**Comment by maciaszczykm** [comment]
@kgroschoff PTAL

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
