### PR TITLE
[release/2.14] Enable flatcar for openstack

### PR DESCRIPTION
**Pull request by kgroschoff**
**What this PR does / why we need it**:
Enable flatcar for openstack
Cherrypicked from https://github.com/kubermatic/dashboard/pull/2430

**Special notes for your reviewer**:
cc @kdomanski 

**Release note**:

```release-note
Enable Flatcar Linux for Openstack
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
It probably needs to be rebased.

**Comment by maciaszczykm** [comment]
Nice timing :)

**Comment by kgroschoff** [comment]
yes, just did it in the same minute :D

**Pull request merged**
