### PR TITLE
Add GPU count for Azure instances

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/3135

**Special notes for your reviewer**:

**Release note**:

```release-note
Added info about GPU count for Azure instances.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Zrzut ekranu 2021-03-5 o 12 30 45

/assign @kgroschoff @floreks

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
