### PR TITLE
Fix issue with watching system color scheme and edition e2e tests

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/3035

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
E2E for CE passed. 

/retest

**Comment by maciaszczykm** [comment]
TIL to be more careful with RxJS imports... It was causing the issue with E2E tests for EE. In some of the places we were using `BehaviorSubject` imported from `rxjs/BehaviorSubject` instead of `rxjs`. This was working during regular serve but we have different configuration for E2E and it was failing because of different implementations in these modules (error was connected to the missing constructor).

@kgroschoff @floreks PTAL

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
