### PR TITLE
Allow audit policy preset changes during cluster edit

### PR DESCRIPTION
**Pull request by maciaszczykm**
### What this PR does / why we need it
Zrzut ekranu 2021-11-30 o 12 49 48

### Which issue(s) this PR fixes
Closes https://github.com/kubermatic/edgematic/issues/74.

### Release note
```release-note
Allow audit policy preset changes during cluster edit.
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Comment by maciaszczykm** [comment]
@kgroschoff I had to fix one issue. Please check the change again.

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
