### PR TITLE
Use new cluster version API endpoint

### LINKED ISSUE #3647: Fetch available K8s versions in relation to the provider
**What would you like to be added? / User Story:**

Since vSphere CSI-driver does not support K8S v1.22 yet, we add the possibility to filter out some Kubernetes versions in relation to the provider. To do so, a new [endpoint](https://github.com/kubermatic/kubermatic/blob/1b65254689f215a591c330803d4c60213705a886/pkg/handler/v2/routes_v2.go#L535-L538) (`/api/v2/providers/{provider_name}/versions`) should be used when fetching available K8s versions during the cluster creation. This endpoint should be used instead of the old one (`/api/v1/upgrades/cluster?type=kubernetes`).

### PR DESCRIPTION
**Pull request by floreks**
### What this PR does / why we need it
Using a new `providers/{provider_name}/versions` endpoint to list cluster versions.

### Which issue(s) this PR fixes

Closes #3647

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Comment by kgroschoff** [comment]
/hold

Seems like version endpoint is not working for bringyourown :trollface: 
https://minio.worker.ci.k8c.io/dashboard-cypress-artifacts/pr-3654-pre-dashboard-test-e2e-1434769744090632192/videos/stories/admin-settings/dynamic-datacenters.spec.ts.mp4

**Comment by mlavacca** [comment]
> /hold
> 
> Seems like version endpoint is not working for bringyourown :trollface:
> https://minio.worker.ci.k8c.io/dashboard-cypress-artifacts/pr-3654-pre-dashboard-test-e2e-1434769744090632192/videos/stories/admin-settings/dynamic-datacenters.spec.ts.mp4

Issue solved by https://github.com/kubermatic/kubermatic/pull/7676
/unhold

**Pull request merged**
