### PR TITLE
Move show all projects to the project list view

### PR DESCRIPTION
**Pull request by floreks**
**What this PR does / why we need it**:
Move show all projects toggle back to the project list view.

Zrzut ekranu z 2020-08-12 15-15-43

Zrzut ekranu z 2020-08-12 15-15-49

**Release note**:

```release-note
Moved "Show All Projects" toggle back to the project list.
```

### CODE REVIEW

**Comment by floreks** [comment]
@cschieder PTAL

**Comment by cschieder** [comment]
works for me

**Pull request merged**
