### PR TITLE
add method to appdef list endpoint

### LINKED ISSUE #5222: Application method and source information missing in cluster template
### What happened
After recent API changes to applications (https://github.com/kubermatic/dashboard/pull/5184), `method` and `source` information is missing from applications data in cluster template.
Due to this change, `method` and `source` details cannot be displayed for applications in cluster template dialog:

screenshot-localhost_8000-2022 10 06-21_59_16

### Expected behavior
`method` and `source` information is present in applications of cluster template.

### PR DESCRIPTION
**Pull request by SimonTheLeg**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #5222 

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:
To fix what is shown in the screenshots of the original issue, only the field method is required if I understand it correctly. This is added with this PR. Currently this PR purposefully does not include the source field, as it is not required for the versions. Additionally including the source is also a bit more tricky and produces a much larger body, as the source is specified per version of an application.

image
(Screenshot from the create clustertemplate dialogue)

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
@SimonTheLeg original issue was about Applications in a cluster template and those screenshots (in attached issue) are not from "Create Cluster Template" (which opens the wizard), but those are from "Create Cluster from Template" dialog which is opened from Cluster Templates page. On that dialog we don't load application definitions but only load `applications` from cluster template data. So I think that issue won't be solved by changes in this PR.

https://user-images.githubusercontent.com/13975988/214612359-dec831e9-049d-426f-9d88-7dba0ce58485.mov


That being said, adding `method` in Application Definition list is still helpful since it will help in fixing another [issue](https://github.com/kubermatic/dashboard/issues/5598). But at the same time, since `source` information is not present in Application Definition List so in order to display source icon I might have to cross reference Application Definition from Application Installations and then load details of those Application Definitions.

**Comment by SimonTheLeg** [comment]
@Waseem826 

I see. Luckily it looks like this is fixed as well :)

image

**Comment by Waseem826** [comment]
@SimonTheLeg I think this only fixed the Mode icon but Source icon will still not work. This can be tested if method and source are not the same (e.g. `Helm` and `Git`).

**Comment by Waseem826** [comment]
https://github.com/kubermatic/dashboard/pull/5630 will fix the original issue.

**Comment by SimonTheLeg** [comment]
okay so if I readd the attached PR correctly, then we wanted to display both source and method if they differ. This I did not know about. Okay understood, for this then it makes more sense to directly fetch teh appdef.

If I understand the FE PR correctly this means we do not need this BE PR here anymore, right @Waseem826?

**Comment by Waseem826** [comment]
Yes @SimonTheLeg. We can close this PR I think.

**Pull request closed without merging**
