### PR TITLE
Update design.md

### PR DESCRIPTION
**Pull request by cschieder**
**What this PR does / why we need it**:
updating the design issue template
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```None```

### CODE REVIEW

**Comment by kgroschoff** [comment]
/hold cancel
Teamwork with @cschieder 😄 
PTAL @maciaszczykm

**Comment by maciaszczykm** [comment]
😄 

/lgtm

**Pull request merged**
