### PR TITLE
[release/v2.14] Fix build/push for the CE image (#2431)

### PR DESCRIPTION
**Pull request by kdomanski**
This is a manual cherry-pick of #2431

```release-note
NONE
```

### CODE REVIEW

**Comment by floreks** [comment]
I guess we also need e2e fix commit here to make e2e pass.

**Comment by kdomanski** [comment]
@floreks are you talking about #2426 ?

**Comment by floreks** [comment]
@kdomanski yep.

**Comment by maciaszczykm** [comment]
Will be done from https://github.com/kubermatic/dashboard/pull/2436.

**Pull request closed without merging**
