### PR TITLE
Fix labels view

### LINKED ISSUE #3716: Fix label display
Zrzut ekranu 2021-09-22 o 13 51 48

It happens i.e. after creating cluster from template.

### PR DESCRIPTION
**Pull request by kgroschoff**
### What this PR does / why we need it
Fixed labels view, as long labels were a problem

break-word

### Which issue(s) this PR fixes

Fixes #3716

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
PTAL @maciaszczykm :)

**Comment by maciaszczykm** [comment]
Great :)

\lgtm

**Comment by kgroschoff** [comment]
As discussed in daily:
/cherrypick release/v2.18

**Comment by kgroschoff** [comment]
btw @maciaszczykm just noticed that you need to lgtm again as `\lgtm` isn't entirely working 😅

**Comment by maciaszczykm** [comment]
@kgroschoff You will need to wait for https://github.com/kubermatic/dashboard/pull/3707 as it will fix the CI issues.

**Pull request merged**
