### PR TITLE
[release/v2.19] Bump version to 2.19.10

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
Bumps the version to v2.19.10 so we can release an out-of-band set of patches for KKP.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by embik** [comment]
It seems @Waseem826 isn't in the OWNERS file for 2.19, so I've also requested a review from @lsviben.

**Pull request merged**
