### PR TITLE
Skip provider tests in community edition and update the images

### PR DESCRIPTION
**Pull request by maciaszczykm**
### Which issue(s) this PR fixes
Closes https://github.com/kubermatic/dashboard/issues/3713.

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/retest

@kgroschoff Please take a look.

**Review by kgroschoff — COMMENTED** [review]
/lgtm
/retest

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
