### PR TITLE
Change Packet to Equinix Metal

### PR DESCRIPTION
**Pull request by maciaszczykm**
### What this PR does / why we need it
It renames most of the user-facing provider naming from Packet to Equinix Metal. Classes and file names were changed too. At the moment it is not possible to change properties (i.e. `cluster.spec.cloud.packet`) as this has to be done in the backend first, then we can adjust the UI and start deprecation for old Packet endpoints.

Zrzut ekranu 2021-09-27 o 13 18 22

### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/3696.

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @kgroschoff 

/hold

For @shaase-ctrl approval.

**Comment by maciaszczykm** [comment]
@zreigz @lsviben Creating new endpoints for Equinix Metal based on the current ones for Packet would allow us to complete the rename process. What do you think?

**Comment by lsviben** [comment]
> @zreigz @lsviben Creating new endpoints for Equinix Metal based on the current ones for Packet would allow us to complete the rename process. What do you think?

Agree, we could add new ones and deprecate the old.

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
