### PR TITLE
Bump version to v2.23.0-beta.1

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
Bump version to v2.23.0-beta.1 to release another beta this week.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
> I think we also need to update version in `package.json` and `package-lock.json` of web module.

Good catch! thank you.

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
