### PR TITLE
Add warning in the wizard when there is no configured seed

### PR DESCRIPTION
**Pull request by maciaszczykm**
### What this PR does / why we need it
Zrzut ekranu 2021-05-24 o 11 26 09

### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/3294.

### Release note
```release-note
Added warning in the wizard when there is no configured seed.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Update:

Zrzut ekranu 2021-05-24 o 11 49 06

**Comment by floreks** [comment]
I'd wait with adding documentation links as it requires some more work to easily maintain it.

/lgtm

**Pull request merged**
