### PR TITLE
Set Azure data disk size default value to 0

### LINKED ISSUE #5973: Azure Data Disk - default should be zero
**What is the problem, where is it and why is it an issue?**
Hi, Currently, when we define machine deployment for Azure - we provide default OS disk and data disk to be 30GB. This causes troubles to the clusters... 
1. as we end up spawining 30GB disk and never using it. 
2. External CSI driver gets confused as it cannot know about this disk and so it thinks that one more disk can be attached to the machine and causes pod startup issues.

**Suggest how to fix it, if possible**
1. Best suggestion is to not provide any possibility to specify this data disk for Azure altogether. This data disk is NEVER usable via Kubernetes automatically.
2. If there is some valid reason to keep this data disk field - default it to `0`.
3. This change is needed in 2 places. a) KKP new cluster wizard, b) New Machine Deployment popup.

### PR DESCRIPTION
**Pull request by Waseem826**
**What this PR does / why we need it**:
Set Azure data disk size default value to `0`.

screenshot-localhost_8000-2023 05 26-17_03_55

**Which issue(s) this PR fixes**:

Fixes #5973 

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Comment by ahmadhamzh** [comment]
i think  maybe we can remove the required error from Data Disk Size field , im not sure do we need it to be 0 or just empty ,
also but not related to you changes we need to set min limit for the field it seems like you can add numbers less than 0

**Comment by Waseem826** [comment]
@ahmadhamzh PR updated.

**Comment by embik** [comment]
@Waseem826 I think this should have a release note since it's a user-facing change.

**Pull request merged**
