### PR TITLE
Update dependency for k8c.io/kubermatic/v2 to `62c8bfb`

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This bumps the `k8c.io/kubermatic/v2` dependency to https://github.com/kubermatic/kubermatic/commit/62c8bfb14ae19969df76f30d387a99dab3734264.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
@embik you probably need to rebase and update swagger spec.

**Comment by ahmedwaleedmalik** [comment]
/approve cancel
To avoid retries

**Comment by embik** [comment]
The swagger error is a weird one, sometimes it passes and sometimes not.

**Pull request merged**
