### PR TITLE
Fix call order in the SSH key view

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/2564

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix loading of the access rights in the SSH keys view.
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
I'm still able to see the ssh keys, but not to add a new one. Is this meant by `User with viewer role sees ssh key management as not greyed out in ui`? 
Asking because when the whole user management was added, this was the requested behaviour: `"sshkeys": {"view": true, "edit": false, "create": false, "delete": false}`. We obviously could change that. Just wondering about the issue 😅 

ssh

Apart from that, code looks good

**Comment by maciaszczykm** [comment]
> Is this meant by User with viewer role sees ssh key management as not greyed out in ui?

Yes, I think so. The view rights are here and backend also supports them. Only the add, edit and delete should be blocked and it wasn't working because of wrong initialization.

**Pull request merged**
