### PR TITLE
[release/v2.22] Patch release version bump, KKP update

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
What the title says.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Review by Waseem826 — APPROVED** [review]

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
