### PR TITLE
Fix issue with Openstack preset creation 

### LINKED ISSUE #4323: Domain is not required when using application credentials
**What happened?**:

Right now `domain` is a required field when we are using application credentials for OpenStack. This field is not required when using application credentials, so it should be removed.

Screenshot 2022-03-16 at 1 16 26 PM

### LINKED ISSUE #4324: Unable to create preset for openstack
Screenshot 2022-03-16 at 1 31 40 PM

### PR DESCRIPTION
**Pull request by floreks**
### What this PR does / why we need it
- Fix an issue with Openstack preset creation

### Which issue(s) this PR fixes

Fixes #4324

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/hold

• Make Domain optional when app credentials are used

Please handle this in a separate PR since this shouldn’t be a part of 2.20. We need to work on this in KKP, API, and machine-controller first.

**Comment by xrstf** [comment]
/override pre-dashboard-test-e2e-ce

under protest

**Pull request merged**
