### PR TITLE
Improve UI/UX

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/2698

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@kgroschoff Can you review it?

/assign @kgroschoff

**Comment by kgroschoff** [comment]
Looks good so far, only noticed two things:

1. The Image Pull Secret hint now is overlaping the Admission Plugings field (reduced window width).
imagepullsecret

2. The Machine Networks Step is gone when selecting Container Linux on VSphere? On dev it's still visible. 🤔

**Comment by maciaszczykm** [comment]
> The Machine Networks Step is gone when selecting Container Linux on VSphere? On dev it's still visible.

I can still see it locally:
Zrzut ekranu 2020-10-22 o 10 06 25

**Comment by kgroschoff** [comment]
Okay, forget about it. Now I can also see it again. 🤔 
Tried it multiple times yesterday as I couldn't see any changes in your code that might be related to it, but it wasn't appearing. But I'm pretty sure that there also wasn't an error in the console... Strange 😅

**Comment by floreks** [comment]
@kgroschoff @maciaszczykm sometimes missing `Machine Network` step issue will be fixed in #2691. I have found a way to reproduce that and fixed it there.

**Comment by maciaszczykm** [comment]
@kgroschoff I've shortened hint message. We should avoid long, multiple line messages in all the places.

Zrzut ekranu 2020-10-22 o 11 58 38

**Comment by kgroschoff** [comment]
Even better 👍 Thanks
/lgtm

**Pull request merged**
