### PR TITLE
Upgrade Angular to version 15

### LINKED ISSUE #5335: Upgrade web application to Angular v15
Upgrade web application to Angular v15 by following instructions in https://update.angular.io/?l=3&v=14.0-15.0. 

Please also update `node` engine version in `package.json` according to requirements of latest Angular version.

### Potential Breaking Changes:
- **Angular Material**
Please follow migration guide (https://github.com/angular/components/blob/main/guides/v15-mdc-migration.md) and verify that the overridden stlyes in our application work with updated Angular Material components.

### PR DESCRIPTION
**Pull request by Waseem826**
**What this PR does / why we need it**:
Upgrade Angular to version 15.

_Current PR Status:_ Pending Angular Material migration from Legacy components to v15 components.

**Which issue(s) this PR fixes**:

Fixes #5335 

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
Created https://github.com/kubermatic/dashboard/issues/5864 epic to migrate Angular Material components from legacy to v15.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

🤞

**Pull request merged**
