### PR TITLE
Update dependencies for API and Web modules

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
This PR updates the dependencies for API and Web modules. It also updates the build image for the prow job to use the latest `KIND` version.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]

**Review by Waseem826 — APPROVED** [review]

**Review by Waseem826 — APPROVED** [review]

**Comment by ahmedwaleedmalik** [comment]
/retest
Hetzner being Hetzner -_-

**Pull request merged**
