### PR TITLE
Fix CE build, improve configs and add missing build check

### PR DESCRIPTION
**Pull request by maciaszczykm**
### What this PR does / why we need it
It changes the way we build and serve different app editions. We can no longer use the `getEditionDirName()` method when picking modules to import as the compiler is checking for the available directories then. The value inside `import()` needs to be constant and we can achieve that by using the file replacements in `angular.json`. Besides that, it adds a few improvements in our config files and job to check if community edition build passes too.

### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/3604.

### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
From my side it looks good.

We just have to keep in mind to also change it for the Allowed Registries: https://github.com/kubermatic/dashboard/pull/3562
I don't mind which pr we merge first though.

**Comment by maciaszczykm** [comment]
PTAL

**Pull request merged**
