### PR TITLE
Dark mode improvements

### PR DESCRIPTION
**Pull request by maciaszczykm**
### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/3398.

### Release note
```release-note
Added multiple styling improvements.
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
Looks good, only a very very small "remark"
`Cluster Create - Change active stepper text color to #66C9FF` - for me the color still is #0072b0 🤔

**Comment by maciaszczykm** [comment]
@kgroschoff Good catch, I must have to mark it by accident. It should be done now.

**Review by kgroschoff — COMMENTED** [review]
No problem :) 

/lgtm

**Pull request merged**
