### PR TITLE
Add search for projects

### PR DESCRIPTION
**Pull request by maciaszczykm**
### Which issue(s) this PR fixes
Fixes https://github.com/kubermatic/dashboard/issues/3420.

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @kgroschoff @floreks 

Please do some manual tests.

**Review by kgroschoff — COMMENTED** [review]
Works very good for me.

I could imagine it would be nice to also filter by owner. Not sure if this is easily doable, but maybe this is something for the future. For now name, labels and id might be enough :)

Maybe @floreks also want to test?

**Pull request merged**
