### PR TITLE
Add changelog support and help panel

### LINKED ISSUE #3055: [Changelog] Add UI support
- [ ] Add dedicated changelog JSON file
- [ ] Support user settings option to correctly show changelog only when required
- [ ] Implement and style the changelog itself

### PR DESCRIPTION
**Pull request by floreks**
**What this PR does / why we need it**:
- Added `Help & Support` section to the top bar
- Added Changelog support
  - it is read from the `assets/config/changelog.json`
  - it will be displayed after every release automatically once the version number changes (after logging in or refreshing the application on the projects view)
  - clicking `Got it` saves the last seen changelog version to the user settings automatically and it then can be only opened through help & support panel
- updated Makefile as our dev build had an empty version number
- Fixed badge display
- Small fixes for API documentation view styling
- Added `date` info to our version structure

Changelog JSON I have used for tests:
```json
{
  "entries": [
    {
      "category": "action-required",
      "description": "Added logos and descriptions for the addons. In order to see the logos and description, addons have to be configured with AddonConfig CRDs with the same names as addons."
    },
    {
      "category": "api",
      "description": "Kubernetes End-of-Life for v1.14 support ended."
    },
    {
      "category": "api",
      "description": "The authorized_keys files on nodes are now updated whenever the SSH keys for a cluster are changed"
    },
    {
      "category": "interface",
      "description": "Added User Settings, Cluster Addons management, RBAC management functionality and new Project View",
      "links": [
        {
          "url": "https://docs.kubermatic.com/kubermatic/v2.16/installation/compatibility/",
          "caption": "User Guide"
        },
        {
          "url": "https://docs.kubermatic.com/kubermatic/v2.16/installation/compatibility/",
          "caption": "Tutorial"
        }
      ]
    },
    {
      "category": "infrastructure",
      "description": "Cluster namespaces could end up stuck in Terminating state when deleting a cluster"
    },
    {
      "category": "machine-controller",
      "description": "Added support for external Cloud Controller Manager"
    }
  ]
}
```

Zrzut ekranu z 2021-02-15 16-57-03

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3055

**Release note**:

```release-note
Add changelog support
```

### CODE REVIEW

**Comment by cschieder** [comment]
Hey some small design adjustments

I think the colors would be better like this
Action Required - info/noncritical warning color
API - `#1B658F`
Interface - button color
Infrastructure - `#1C8282`
Machine Controller - green button color

image

**Comment by floreks** [comment]
@cschieder do you want to adjust colors for the dark theme or do you think they are ok?

Zrzut ekranu z 2021-02-19 12-13-27

**Comment by cschieder** [comment]
Thanks for the quick change! I think they're fine

**Comment by kgroschoff** [comment]
Overall it looks good, just accidentally noticed, that it is not possible to close the dialog when you automatically get logged out by the system. Is it somehow possible to also close it if you aren't authenticated?

**Comment by floreks** [comment]
> Overall it looks good, just accidentally noticed, that it is not possible to close the dialog when you automatically get logged out by the system. Is it somehow possible to also close it if you aren't authenticated?

Shouldn't be hard to check for this. Good catch.

**Comment by maciaszczykm** [comment]
@floreks I've noticed one small thing that you can adjust. The scrollbar is defined on some of the internal elements because it is not close to the dialog border like in the machine deployment dialog:

Zrzut ekranu 2021-02-22 o 08 42 11

**Comment by maciaszczykm** [comment]
From the code perspective it looks good.

**Comment by floreks** [comment]
Fixed the scroll container
Zrzut ekranu z 2021-02-22 10-18-31

**Pull request merged**
