### PR TITLE
[release/v2.26] Bump KKP, MC, and OSM dependencies to latest

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Bump KKP, MC, and OSM dependencies to the latest available modules for KKP 2.26.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/hold

Waiting for https://github.com/kubermatic/kubermatic/pull/13813 to be merged

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
