### PR TITLE
Enable OSM by default during cluster creation

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:

**Which issue(s) this PR fixes** :

Fixes #

**Special notes for your reviewer**:

**Release Note**:

```release-note
NONE
```
/hold

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/test pre-dashboard-test-e2e-ce 

Pod was not scheduled

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
