### PR TITLE
Do not allow HTML inside notification messages

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard/issues/2871

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @floreks @kgroschoff 

Can one of you review it?

**Comment by xrstf** [comment]
I find it a bit sad that because of fixing the XSS vulnerability, this PR also reduces the readability by removing the <strong> tags in the popups. The bold font was pretty nice IMHO.

**Comment by floreks** [comment]
> I find it a bit sad that because of fixing the XSS vulnerability, this PR also reduces the readability by removing the <strong> tags in the popups. The bold font was pretty nice IMHO.

The XSS vulnerability was actually never there as by default Angular applies `sanitize(SecurityContext.HTML, htmlString)` when `innerHTML` attribute is used and the result string is always guaranteed to be secure. Only basic HTML was interpreted there. On the other hand it was possible to provide clickable links or embedded images that could allow other attacks, i.e. phishing.

**Comment by maciaszczykm** [comment]
Yeah, exactly. The previous form would need to be changed. We would need to escape all the names and messages coming from the API and then apply our styling elements like `<strong>`. I have removed them completely because in the designs there is no additional styling. We can go back to it though if that's important. @cschieder, what do you think? Should we use bold resource names in the notification messages?

**Review by floreks — APPROVED** [review]
/lgtm

**Pull request merged**
