### PR TITLE
Redesign autocomplete inputs

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: Improves the autocompletion components that I've added recently for some of the provider fields.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes https://github.com/kubermatic/dashboard/issues/2933

**Special notes for your reviewer**: Adding confirmation arrow once the data load is completed is quite complex as in case of the errors we would need to show some other icon. If we still want to add this I'd move this to the another issue and iterate on it later.

Panel is not visible until the data is loaded like in other selectors/comboboxes.

**Release note**:

```release-note
Redesigned autocomplete inputs. Right now spinner will be displayed next to the input that loads autocompletions in the background.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @kgroschoff @floreks 

Can one of you take a look? The best place to check the changes is Azure where there are multiple autocomplete components.

**Review by kgroschoff — COMMENTED** [review]
/lgtm
Maybe we could add a dropdown arrow once the data is loaded? If no data is available the icon won't appear, that might be indicator enough? But agree, that this can be something for later improvement - if we still want to improve further.

Not sure if you want other opinions, so feel free to cancel if needed
/hold

**Comment by maciaszczykm** [comment]
/hold cancel

@kgroschoff Thanks. I'll check the Material guidelines.

cc @cschieder

**Comment by maciaszczykm** [comment]
I cannot find anything good in the Material Design docs. The Angular Material implements it without arrow, however, it's fine for me to add it later.

**Pull request merged**
