### PR TITLE
[release/v2.22] Update web for v2.22.6 patch release

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
Prepare dashboard for 2.22.6 patch release.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
Please also update the root `Makefile`

**Comment by ahmedwaleedmalik** [comment]
Release notes need to be adjusted for https://github.com/kubermatic/dashboard/pull/6173

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
