### PR TITLE
Update KubeVirt logo to mark technology preview

### PR DESCRIPTION
**Pull request by Waseem826**
**What this PR does / why we need it**:
screenshot-localhost_8000-2022 08 11-16_44_32

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind design

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update KubeVirt logo to mark technology preview.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
@csengerszabo do we need this change in both v2.19 and v2.20?

**Comment by csengerszabo** [comment]
> @csengerszabo do we need this change in both v2.19 and v2.20?

yes

**Pull request merged**
