### PR TITLE
Bump version to 2.19.8

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:

**Which issue(s) this PR fixes** :

Fixes #

**Special notes for your reviewer**:

**Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by Waseem826** [comment]
/retest
It keeps failing on different test every time.

**Comment by Waseem826** [comment]
I can't approve this PR since I'm not in Owners list in v2.19 version branch

**Comment by ahmedwaleedmalik** [comment]
Sometimes dirty hacks are what you need @Waseem826 :P

**Pull request merged**
