### PR TITLE
[release/v2.20] Show updated config instead of default values in edit machine deployment dialog

### PR DESCRIPTION
**Pull request by Waseem826**
**What does this PR do / Why do we need it**:
Manual cherry pick for #4496 because it couldn't be created automatically: https://github.com/kubermatic/dashboard/pull/4496#issuecomment-1169852457

**Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Review by KhizerRehan — APPROVED** [review]

**Comment by Waseem826** [comment]
@xrstf  can you please override `pre-dashboard-test-e2e`? These tests are flaky (but running fine locally) and the changes in this PR do not have any effect on failing test.

**Comment by Waseem826** [comment]
@xrstf not sure why it reran all builds after override. Can you please override again?

**Pull request merged**
