### PR TITLE
[release/v2.23] Introduce an option to disable admin kubeconfig endpoints

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
This is an automated cherry-pick of [#6208](https://github.com/kubermatic/dashboard/pull/6246)

/kind feature

```release-note
Support for disabling admin kubeconfig endpoint
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/retest

Not related to this PR

**Pull request merged**
