### PR TITLE
Bump version to v2.24.0-beta.0

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
We decided in sig-release to cut a first beta release for v2.24.0 as soon as possible, so here's the PR to prepare that.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

just realised we should probably drop 1.25 support before merging this.

**Comment by embik** [comment]
/hold cancel

doesn't matter, just a beta release. let's not push it out.

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
