### PR TITLE
Added keydown.enter to forms

### LINKED ISSUE #2879: Allow keyboard navigation in forms
**What is the problem, where is it and why is it an issue?**
When I try to create a new project, I intuitively enter the name into the popup:

screenshot-2020-12-15-180741

... and then i press **[ENTER]** on my keyboard and _nothing happens_. :-(

**Suggest how to fix it, if possible**
Some oldschool bois like me are used to web forms treating [ENTER] as "submit the form now". Would be cool if KKP dashboard could treat it the same.

### PR DESCRIPTION
**Pull request by kgroschoff**
**What this PR does / why we need it**:
Wherever possible, added keydown.enter to dialogs to submit the form.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to #2879

**Special notes for your reviewer**:
/

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
PTAL @maciaszczykm

**Comment by maciaszczykm** [comment]
Works well but there is one more approach that we should consider:

```html
<form [formGroup]="form"
      (submit)="onSubmit()">...</form>
```
```html
<button mat-flat-button
        type="submit"
        [disabled]="!form.valid">Save</button>
```

I think it would be a bit better as we would reference the `onSubmit()` function only once in the template. Doesn't matter if the user clicks the button or press enter key the same function would be called. What do you think?

**Comment by kgroschoff** [comment]
Good idea, will change it

**Comment by maciaszczykm** [comment]
Also, I've found https://github.com/kubermatic/dashboard/issues/2891 issue that is related but not caused by this change. It would be nice to solve it in the near future if we want to advertise allowing keyboard navigation as this is closely related issue.

**Comment by kgroschoff** [comment]
Regarding the issue we could add `onkeypress="return event.keyCode != 13;"` to the input fields from the label form. Not sure if this is the best option, but I know that it is working 😅

**Comment by maciaszczykm** [comment]
@kgroschoff Could be a temporary solution until we will find something better. It's probably something with labels form.

**Comment by kgroschoff** [comment]
@maciaszczykm I added it to this pr for now. Should we nevertheless let the issue open with a comment?

**Comment by maciaszczykm** [comment]
@kgroschoff Yes. I've removed the comment because I am not sure about this but let's keep it. Issue should stay open because it needs to be improved.

/lgtm

**Comment by maciaszczykm** [comment]
By the way, I think this may be a good point for a changelog. It's quite good improvement of UX.

**Comment by maciaszczykm** [comment]
The edit project dialog is broken after the last change:

Zrzut ekranu 2021-01-4 o 12 35 14

Please verify all other modified forms.

**Comment by maciaszczykm** [comment]
@kgroschoff I've fixed the issue with labels in https://github.com/kubermatic/dashboard/pull/2903.

**Comment by maciaszczykm** [comment]
@kgroschoff To associate buttons with forms you can use `form` attribute of the `button` element. Check this out: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by kgroschoff** [comment]
@maciaszczykm finally... PTAL
problem for failing tests: `mat-dialog-close` doen't work in combination with `type="submit"` :ok_woman:

**Comment by maciaszczykm** [comment]
Good to know :) I think we should close the dialog from the handler method if we are using submit button.

**Comment by kgroschoff** [comment]
Yes, we're already closing the dialog within `deleteCluster()` (problem appeared in cluster delete dialog) so this was already kind of duplicated.

**Comment by maciaszczykm** [comment]
I'll review tomorrow.

**Comment by maciaszczykm** [comment]
There are some of the fields that are not covered:
- datacenter dialogs in the admin panel - probably skipped because of the multi-line editor at the end
- connect cluster dialog - as above
- delete service account dialog - on pressing enter the dialog closes, would be good to change this and other confirmation dialogs too
- wizard - it seems complex enough to be additional pull request but perhaps we should do it before we will state that key navigation is enabled in the app

**Comment by maciaszczykm** [comment]
/lgtm

Let's merge and adjust other places from the next pull request.

**Comment by kgroschoff** [comment]
Thanks @maciaszczykm I will have a look and take care in a new pr. Removed the release note for now

**Comment by maciaszczykm** [comment]
If the wizard or any other place will require too much effort then I'd leave it as it is. If there will be any incoming requests about this then we can rethink.

**Pull request merged**
