### PR TITLE
Add `errorMessage` field to `GET /api/v2/projects/{project_id}/clusters` response

### LINKED ISSUE #5919: Decorate cluster list API response with field indicating that it doesn't contain complete list
**What would you like to be added? / User Story**:

As API user, I'd like to know if there were some problems while listing user-clusters.
Currently, if there is a problem with seed connection, we return an incomplete list with clusters collected only from reachable seeds.
The idea is to add an additional field in the response to indicate that user-cluster list is not full.

ref: 
- https://github.com/kubermatic/dashboard/issues/5913
- https://github.com/kubermatic/dashboard/pull/5226

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:

If there is any problem connecting to any of seeds while `GET /api/v2/projects/{project_id}/clusters`, error message is only logged in the backend and clusters located on that broken seed aren't added to the response. From the UI perspective, there is no way to tell if something went wrong. 

This PR wraps `GET /api/v2/projects/{project_id}/clusters` cluster list response with an object containing `clusters` field  and optional `errorMessage` field. `clusters` field contains just a regular list of clusters. The content of `errorMessage` is different depending on user type:
- for admins it's richer, meaning it contains names of problematic seeds,
- for regular users it's only a generic information that something went wrong.

**Which issue(s) this PR fixes**:

Fixes #5919 

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by pkprzekwas** [comment]
/hold

Let's discuss this solution on sig-api-ui meeting.

**Comment by pkprzekwas** [comment]
/unhold 

issue has been discussed on sig-api-ui

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
