### PR TITLE
Use the new seed endpoint and refactor the datacenters handling

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: Introduces usage of the seed endpoint and fixes a few of datacenter related issues.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Related to https://github.com/kubermatic/dashboard/issues/2252. Unblocks https://github.com/kubermatic/kubermatic/pull/5562.

**Special notes for your reviewer**:

- Seed datacenters are now referenced as `seed`, "normal" datacenters are referenced as `datacenter` (in most of the places, I'm not sure if I've managed to cover everything yet).
- It seems like the admission plugin configuration (i.e. `datacenter.spec.enforcePodSecurityPolicy`) exists on datacenter not seed level. This means few changed were required in `edit-cluster.component.ts` as `this.datacenter` was actually a seed not datacenter.
- Same as above for `isImageAvailableForVsphere()` method from `node-data.component.ts`.

/cc @kgroschoff @floreks 
Please verify.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
It's ready for review @kgroschoff @floreks. I will do manual testing right now.

/hold

**Comment by kgroschoff** [comment]
Looks good to me. Also tested it locally and it seems to work pretty well. 👍 
As this is a bigger change, maybe @floreks should also have a look?

**Comment by maciaszczykm** [comment]
@kgroschoff Agree, let's wait for @floreks.

**Pull request merged**
