### PR TITLE
Upgrade to Angular version 17

### LINKED ISSUE #6630: Upgrade to Angular 17
We can follow https://update.angular.io/?l=3&v=16.0-17.0 to upgrade to Angular 17. Although we are running into https://github.com/angular/angular-cli/issues/26702.

### PR DESCRIPTION
**Pull request by Waseem826**
**What this PR does / why we need it**:
Upgrade to Angular version 17.

**Which issue(s) this PR fixes**:

Fixes #6630 

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by Waseem826** [comment]
@ahmadhamzh Unit tests are marked as optional for now and should be fixed as part of Angular Material components migration. See https://github.com/kubermatic/dashboard/issues/5864#issuecomment-2015277402

**Review by ahmadhamzh — APPROVED** [review]
/lgtm

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 this needs a release note

**Pull request merged**
