### PR TITLE
KubeVirt: Support for VPC and Subnets

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Builds on top of https://github.com/kubermatic/machine-controller/pull/1862 and adds support on UI for using VPC at cluster level and subnets and machine level.

## Short demonstration of the feature

https://github.com/user-attachments/assets/94732690-3ffb-41cd-a938-7a26b2f1b16b

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Support for Kube-OVN subnet and VPCs for KubeVirt
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by moadqassem** [comment]
@ahmedwaleedmalik Any idea what we need to do to get this PR merged ?

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik Any idea what we need to do to get this PR merged ?

We couldn't test it previously because of the issues with dev. @Waseem826 is currently reviewing it and i'm testing the final parts.

**Review by Waseem826 — APPROVED** [review]
/approve

**Pull request merged**
