### PR TITLE
Update event grouping and more information section logic

### LINKED ISSUE #4116: Cluster Event List - Improvements
image

Two points
1) when I last talked with @toschneck he told me how the grouping of the notifications is rather slow or sometimes doesn't seem to happen at all, then we have the same event in the list a few times
2) resource id and cluster should probably not have a line break

### PR DESCRIPTION
**Pull request by floreks**
### What this PR does / why we need it
- Additional custom events grouping by the message/type/id
- Expand additional information section by default when cluster is not in running state

### Which issue(s) this PR fixes

Fixes #4116

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by floreks** [comment]
I'd just override this as it's a weird flake.

**Comment by xrstf** [comment]
Shall I?

**Pull request merged**
