### PR TITLE
Update scrollbar styling

### PR DESCRIPTION
**Pull request by maciaszczykm**
### What this PR does / why we need it
Zrzut ekranu 2021-11-9 o 11 38 51

### Which issue(s) this PR fixes
Closes https://github.com/kubermatic/dashboard/issues/3833.

### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
Not sure where exactly it is coming from, but vertical + horizontal scrollbar is looking strange now. Can you take a look on it?
scrollbar

**Comment by maciaszczykm** [comment]
@kgroschoff Sure, I will check this.

**Comment by maciaszczykm** [comment]
Zrzut ekranu 2021-11-12 o 11 24 55

Done. I've also found an issue with our sidebar that is on master for some time I think, see: https://github.com/kubermatic/dashboard/issues/3850.

**Review by kgroschoff — COMMENTED** [review]
Good catch!

/lgtm

**Pull request merged**
