### PR TITLE
Bump Angular to v10, TypeScript to 3.9 and use ESNext

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: https://volosoft.com/blog/what-is-new-in-angular-10

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes https://github.com/kubermatic/dashboard/issues/2448.

**Special notes for your reviewer**: 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@kgroschoff It seems that I have find solution for the existing issues:

- Font Awesome is now completely removed. It was mainly used to display solid circle (status icon) and loading spinner that were replaced by custom SVGs. There were also 2-3 icons that were replaced by Material Icons.
- ngx-custom-validators had to be reverted to v8.0.0 as it was not working after Angular update.
- Ubuntu font is now installed with fontsource-ubuntu dependency, thanks to it we are not keeping any font assets in our src directory.
- ES5 is no longer supported by Angular 10, I've switched to "exnext" that should allow us to follow the updates.

Please take a look :)

**Comment by maciaszczykm** [comment]
Build was failing because Subject was imported from rxjs/Subject instead from rxjs directly in a few places. Good to remember for the future.

**Comment by kgroschoff** [comment]
Nice work 👍 

I only noticed one error in the browser console:
```
Refused to apply style from 'http://localhost:8000/assets/fonts/material_icons/material-icons.css' because its MIME type
('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
Do you also see it?

Otherwise LGTM, couldn't find any other problems 👍

**Comment by maciaszczykm** [comment]
@kgroschoff It is fixed now. There was a reference to the old file.

**Comment by kgroschoff** [comment]
Great 😃 
/lgtm

**Comment by kgroschoff** [comment]
/hold
not sure if you want to merge other stuff first. feel free to unhold :)

**Pull request merged**
