### PR TITLE
Fix switch for sharing cluster

### LINKED ISSUE #6329: `enableShareCluster` button in Kubermatic settings doesn't work
### What happened
Clicking on `enableShareCluster` checkmark doesn't update the value in KubermaticSettings.

### Expected behavior
Value is persisted in etcd after request is processed by API.

### How to reproduce
Go to Admin Settings and try clicking on `enableShareCluster` checkmark.

### Environment
- UI Version: 2.24.beta
- API Version: 2.24.beta
- Domain: https://kkp.qa.lab.kubermatic.io

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
This PR changes the type of `enableShareCluster` to bool pointer in order to avoid defaulting this value to `true` each time settings are updated.

**Which issue(s) this PR fixes**:
Fixes #6329 

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix `Enable Share Cluster` button in Admin Settings.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]
/approve

**Review by Waseem826 — APPROVED** [review]

**Review by embik — APPROVED** [review]

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
cc @kubermatic/sig-release-managers

**Comment by embik** [comment]
/retest

🤞🏻

**Pull request merged**
