### PR TITLE
Show/Hide share cluster button from admin default settings

### LINKED ISSUE #5503: Adding an option to show/hide Share Config in Admin Panel
**What is the problem, where is it and why is it an issue?**
Currently, "Share" config option on the user cluster screen button is toggled based on config defined in `config.json` file under assets dir. Currently, there is no option to show/hide share button from "/settings/defaults" as an admin just like we have other buttons e.g WebTerminal, K8's Dashboard.

Also removing the defaulting of share_kubeconfig from being set in kubermatic configuration in backend
- Remove default [share cluster config](https://github.com/kubermatic/dashboard/blob/main/modules/web/src/assets/config/config.json#L6) from assets folder
-  Update theme docs 

**Suggest how to fix it, if possible**
- New option to be returned from settings endpoint API

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What this PR does / why we need it**:

This PR allows to handle share cluster button to show/hide from Admin Setting defaults section. This will allow to control [share cluster kubeconfig button](https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/oidc-provider-configuration/share-clusters-via-delegated-oidc-authentication/) to be handled from Admin default settings page instead of providing defaulting from [UI](https://github.com/kubermatic/dashboard/pull/5764/files#diff-d82c3bf00b3add2232bb68e05398a1f829a6f9e82028938d736a6d39bf5cf3c7L6).

Adds new setting Interface. Defaults page

new-switch

**Which issue(s) this PR fixes**:

Fixes #5503 

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Introduce Enable Share Cluster settings to toggle the share cluster feature from Admin panel.
```

**Documentation**:

[Update Doc](https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/dashboard-customization/#preparing-a-new-theme-with-access-to-the-sources)

```documentation
TBD
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]

**Comment by ahmedwaleedmalik** [comment]
@KhizerRehan please add a release note

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/unhold

**Pull request merged**
