### PR TITLE
Support for edge provider in KKP API

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Support for edge provider in KKP API
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]

**Comment by Waseem826** [comment]
/lgtm
Sorry I approved too soon 😅

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
